config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get '/', to: 'welcome#index', as: 'home'
  #Dealer Parent
  get '/dealers', to: 'dealers#index', as: 'dealers'
  get '/dealers/new', to: 'dealers#new', as: 'new_dealer'
  post '/dealers', to: 'dealers#create', as: 'create_dealer'
  get '/dealers/:id', to: 'dealers#show', as: 'show_dealer'
  get '/dealers/:id/edit', to: 'dealers#edit', as: 'edit_dealer'
  patch '/dealers/:id', to: 'dealers#update', as: 'update_dealer'
  delete '/dealers/:id', to: 'dealers#destroy', as: 'destroy_dealer'


  #Roads Parent

  get '/roads', to: 'roads#index'
  get '/roads/new', to: 'roads#new'
  post '/roads/new', to: 'roads#create'
  get '/roads/:id', to: 'roads#show'
  patch '/roads/:id', to: 'roads#update'
  get '/roads/:id/edit', to: 'roads#edit'
  delete '/roads/:id', to: 'roads#destroy'

  # Cars Child Roads Parent
  get '/cars', to: 'cars#index'
  get '/cars/:id', to: 'cars#show'
  get '/roads/:id/cars/new', to: 'cars#new'
  post '/roads/:id/cars', to: 'cars#create'
  get '/cars/:id/edit', to: 'cars#edit'
  patch '/cars/:id', to: 'cars#update'
  delete '/cars/:id', to: 'cars#destroy'

  # Trucks Child Dealer Parent
  get '/trucks', to: 'trucks#index', as: 'trucks', as: 'trucks'
  get '/dealers/:id/trucks/new', to: 'trucks#new', as: 'new_truck'
  post '/dealers/:id/trucks', to: 'trucks#create', as: 'create_truck'
  get '/trucks/:id/edit', to: 'trucks#edit', as: 'edit_truck'
  patch '/trucks/:id', to: 'trucks#update', as: 'update_truck'
  get '/trucks/:id', to: 'trucks#show', as: 'show_truck'
  delete '/trucks/:id', to: 'trucks#destroy', as: 'destroy_truck'

  get '/dealers/:id/trucks', to: 'trucks_dealer#index', as: 'trucks_dealer'
  get '/roads/:id/cars', to: 'cars_road#index', as: 'cars_road'
end

app/models/truck.rb
class Truck < ApplicationRecord
  belongs_to :dealer

  def self.search_year(search)
    Truck.where("year >= ?", search)
  end

  def self.partial_search(find)
    key = "%#{find}%"

    Truck.where("make || model like :search", search: key)
  end

  def self.exact_search(find)
    key = "#{find}"

    Truck.where("make = :finder", finder: key) || Truck.where("make = :finder", finder: key)
  end

  def self.sort_alphabetically
    order('LOWER(make) ASC')
  end
end

app/controllers/trucks_controller.rb
class TrucksController < ApplicationController
  def index
    if params[:search] == ""
      redirect_to trucks_path
    elsif params["commit"] == "Sort"
      @trucks = Truck.sort_alphabetically
    elsif params["commit"] == "search"
      search(params)
    else
      @trucks = Truck.all
    end
  end

  def search(params)
    if params["radio"] == "orderbyyear"
      @trucks = Truck.search_year(search_params[:search])
    elsif params["radio"] == "Exact Match"
      @trucks = Truck.exact_search(search_params[:search])
    elsif params["radio"] == "Partial"
      @trucks = Truck.partial_search(search_params[:search])
    end
  end

  def new
  end

  def create
    if params[:make] == ""
      redirect_to new_truck_path(params[:dealer_id], :dealer_id => params[:dealer_id])
    else
      truck = Truck.new(truck_params)
      truck.save
      redirect_to trucks_dealer_path(truck.dealer_id)
    end
  end

  def show
    @truck = Truck.find(params[:id])
  end

  def edit
    @truck = Truck.find(params[:id])
  end

  def update
    if params[:make] == ""
      redirect_to edit_truck_path(params[:id])
    else
      truck = Truck.find(params[:id])
      truck.update!(truck_params)
      redirect_to show_truck_path(truck.id)
    end
  end

  def destroy
    truck = Truck.select(:dealer_id).find(params[:id])
    Truck.destroy(params[:id])
    redirect_to trucks_dealer_path(truck.dealer_id)
  end

  private

  def truck_params
    params.permit(:year, :make, :model, :dealer_id)
  end

  def search_params
    params.permit(:search)
  end
end

app/views/trucks/edit.html.erb
<%= form_tag update_truck_path(@truck.id), method: :patch do %>
  <%= label_tag 'year:' %>
  <%= text_field_tag :year %><br>
  <%= label_tag 'make:' %>
  <%= text_field_tag :make %><br>
  <%= label_tag 'model:' %>
  <%= text_field_tag :model %><br>
  <div>
    <%= submit_tag "update" %>
  </div>
<% end %>

app/views/trucks/index.html.erb
<html>
  <head>
  </head>

  <body>
    <ul class="navbar">
      <li><%= link_to "Home Page", home_path, method: :get %></li>
      <li><%= link_to "Dealers Page", dealers_path, method: :get %></li>
    </ul>
    <h2>Welcome to the Trucks Collective Inventory Page</h2>
    <%= form_tag trucks_path, method: :get  do %>
      <%= label_tag 'Sort by make/model?' %>
      <div>
        <%= submit_tag 'Sort' %>
      </div>
    <% end %>
    <%= form_tag trucks_path, method: :get do %>
      <%= label_tag 'Search by year/make/model:' %>
      <h3><%= text_field_tag "search" %></h3>
      <%= label_tag 'Exact:' %>
      <%= radio_button_tag 'radio', 'Exact Match' %>
      <%= label_tag 'Partial:' %>
      <%= radio_button_tag 'radio', 'Partial' %>
      <%= label_tag 'Year:' %>
      <%= radio_button_tag 'radio', 'orderbyyear', required: :required %>
      <div>
        <%= submit_tag 'search' %>
      </div>
    <% end %>
    <table>
      <tr>
        <th>View Truck</th>
        <th>Year</th>
        <th>Make</th>
        <th>Model</th>
        <th>Dealer</th>
        <th>Edit</th>
        <th>Delete</th>
      </tr>
    <% @trucks.each do |truck| %>
      <tr>
        <td><%= link_to "View", show_truck_path(truck.id), method: :get %></td>
        <td><%= truck.year %></td>
        <td><%= truck.make %></td>
        <td><%= truck.model %></td>
        <td><%= link_to "#{truck.dealer.name}", show_dealer_path(truck.dealer_id), method: :get %></td>
        <td><%= link_to "Edit", edit_truck_path(truck.id), method: :get %></td>
        <td><%= link_to "Delete", destroy_truck_path(truck.id), method: :delete %></td>
      <tr>
    <% end %>
  </table>
  </body>
<html>

app/views/trucks/new.html.erb
<%= form_tag create_truck_path, method: :post do %>
  <%= hidden_field_tag :dealer_id, params[:id] %>
  <%= label_tag 'year:' %>
  <%= text_field_tag :year %><br>
  <%= label_tag 'make:' %>
  <%= text_field_tag :make %><br>
  <%= label_tag 'model:' %>
  <%= text_field_tag :model %><br>
  <div>
    <%= submit_tag "Create a Truck" %>
  </div>
<% end %>

app/views/trucks/show.html.erb
<head>
</head>
<body>
  <ul class="navbar">
    <li><%= link_to "Home Page", home_path, method: :get %></li>
    <li><%= link_to "Trucks Index", trucks_path, method: :get %></li>
    <li><%= link_to "Edit Truck", edit_truck_path(@truck.id), method: :get %></li>
    <li><%= link_to "Dealer Page", show_dealer_path(@truck.dealer_id), method: :get %></li>
    <li><%= link_to "Delete", destroy_truck_path(@truck.id), method: :delete %></li>
  </ul>
<table>
  <tr>
    <th>Year</th>
    <th>Make</th>
    <th>Model</th>
    <th>Dealer ID</th>
    <th>Dealer Name</th>
  </tr>
  <tr>
    <td><%= @truck.year %></td>
    <td><%= @truck.make %></td>
    <td><%= @truck.model %></td>
    <td><%= @truck.dealer_id %></td>
    <td><%= @truck.dealer.name %></td>
  </tr>
</table>
</body>