config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get '/', to: 'welcome#index', as: 'home'
  #Dealer Parent
  get '/dealers', to: 'dealers#index', as: 'dealers'
  get '/dealers/new', to: 'dealers#new', as: 'new_dealer'
  post '/dealers', to: 'dealers#create', as: 'create_dealer'
  get '/dealers/:id', to: 'dealers#show', as: 'show_dealer'
  get '/dealers/:id/edit', to: 'dealers#edit', as: 'edit_dealer'
  patch '/dealers/:id', to: 'dealers#update', as: 'update_dealer'
  delete '/dealers/:id', to: 'dealers#destroy', as: 'destroy_dealer'


  #Roads Parent

  get '/roads', to: 'roads#index'
  get '/roads/new', to: 'roads#new'
  post '/roads/new', to: 'roads#create'
  get '/roads/:id', to: 'roads#show'
  patch '/roads/:id', to: 'roads#update'
  get '/roads/:id/edit', to: 'roads#edit'
  delete '/roads/:id', to: 'roads#destroy'

  # Cars Child Roads Parent
  get '/cars', to: 'cars#index'
  get '/cars/:id', to: 'cars#show'
  get '/roads/:id/cars/new', to: 'cars#new'
  post '/roads/:id/cars', to: 'cars#create'
  get '/cars/:id/edit', to: 'cars#edit'
  patch '/cars/:id', to: 'cars#update'
  delete '/cars/:id', to: 'cars#destroy'

  # Trucks Child Dealer Parent
  get '/trucks', to: 'trucks#index', as: 'trucks', as: 'trucks'
  get '/dealers/:id/trucks/new', to: 'trucks#new', as: 'new_truck'
  post '/dealers/:id/trucks', to: 'trucks#create', as: 'create_truck'
  get '/trucks/:id/edit', to: 'trucks#edit', as: 'edit_truck'
  patch '/trucks/:id', to: 'trucks#update', as: 'update_truck'
  get '/trucks/:id', to: 'trucks#show', as: 'show_truck'
  delete '/trucks/:id', to: 'trucks#destroy', as: 'destroy_truck'

  get '/dealers/:id/trucks', to: 'trucks_dealer#index', as: 'trucks_dealer'
  get '/roads/:id/cars', to: 'cars_road#index', as: 'cars_road'
end

app/controllers/trucks_dealer_controller.rb
class TrucksDealerController < ApplicationController
  def index
    if params[:search] == ""
      redirect_to trucks_dealer_path(params[:id])
    end
    @dealer = Dealer.find(params[:id])
    if params["commit"] == "Sort"
      @trucks = @dealer.sort_alphabetically
    elsif params["commit"] == "search"
      search(params)
    else
      @trucks = @dealer.trucks
    end
  end

  def search(params)
    @dealer = Dealer.find(params[:id])
    if params["radio"] == "orderbyyear"
      @trucks = @dealer.search_year(search_params[:search])
    elsif params["radio"] == "Exact Match"
      @trucks = @dealer.exact_search(search_params[:search])
    elsif params["radio"] == "Partial"
      @trucks = @dealer.partial_search(search_params[:search])
    end
  end

  private

  def search_params
    params.permit(:search)
  end
end

app/views/trucks_dealer/index.html.erb
<html>
<head>
</head>
<body>
  <ul class="navbar">
    <li><%= link_to "Dealer Page", show_dealer_path(@dealer.id), method: :get %></li>
    <li><%= link_to "Dealers Index", dealers_path, method: :get %></li>
    <li><%= link_to "All Trucks Index", trucks_path, method: :get %></li>
    <li><%= link_to "Adopt A Truck", new_truck_path(@dealer.id, :dealer_id => @dealer.id), method: :get %></li>
  </ul><br/>
  <%= form_tag trucks_dealer_path(@dealer.id), method: :get  do %>
    <%= label_tag 'Sort by make/model?' %>
    <div>
      <%= submit_tag 'Sort' %>
    </div>
    <h3> OR!</h3>
  <% end %>
  <%= form_tag trucks_dealer_path, method: :get do %>
    <%= label_tag 'Search by year/make/model:' %><br>
    <%= text_field_tag "search" %><br/><br>
    <%= label_tag 'Exact:' %>
    <%= radio_button_tag 'radio', 'Exact Match' %>
    <%= label_tag 'Partial:' %>
    <%= radio_button_tag 'radio', 'Partial' %>
    <%= label_tag 'Year:' %>
    <%= radio_button_tag 'radio', 'orderbyyear', required: :required %><br><br>
    <div>
      <%= submit_tag 'search' %>
    </div>
  <% end %>
  <h2>Number of Trucks: <%= @dealer.child_count(:trucks) %></h2>
<table>
  <tr>
    <th>View Truck</th>
    <th>Year</th>
    <th>Make</th>
    <th>Model</th>
    <th>Edit me?</th>

    <th>Stay or go?</th>
  </tr>
    <% @trucks.each do |truck| %>
    <tr>
      <td><%= link_to "View", show_truck_path(truck.id), method: :get %></td>
      <td><%= truck.year %></td>
      <td><%= truck.make %></td>
      <td><%= truck.model %></td>
      <td><%= link_to "Edit", edit_truck_path(truck.id), method: :get %></td>
      <td><%= link_to "Delete Truck", destroy_truck_path(truck.id), method: :delete %></td>
    </tr>
    <% end %>
  </table>
</body>
</html>