config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get '/', to: 'welcome#index', as: 'home'
  #Dealer Parent
  get '/dealers', to: 'dealers#index', as: 'dealers'
  get '/dealers/new', to: 'dealers#new', as: 'new_dealer'
  post '/dealers', to: 'dealers#create', as: 'create_dealer'
  get '/dealers/:id', to: 'dealers#show', as: 'show_dealer'
  get '/dealers/:id/edit', to: 'dealers#edit', as: 'edit_dealer'
  patch '/dealers/:id', to: 'dealers#update', as: 'update_dealer'
  delete '/dealers/:id', to: 'dealers#destroy', as: 'destroy_dealer'


  #Roads Parent

  get '/roads', to: 'roads#index'
  get '/roads/new', to: 'roads#new'
  post '/roads/new', to: 'roads#create'
  get '/roads/:id', to: 'roads#show'
  patch '/roads/:id', to: 'roads#update'
  get '/roads/:id/edit', to: 'roads#edit'
  delete '/roads/:id', to: 'roads#destroy'

  # Cars Child Roads Parent
  get '/cars', to: 'cars#index'
  get '/cars/:id', to: 'cars#show'
  get '/roads/:id/cars/new', to: 'cars#new'
  post '/roads/:id/cars', to: 'cars#create'
  get '/cars/:id/edit', to: 'cars#edit'
  patch '/cars/:id', to: 'cars#update'
  delete '/cars/:id', to: 'cars#destroy'

  # Trucks Child Dealer Parent
  get '/trucks', to: 'trucks#index', as: 'trucks', as: 'trucks'
  get '/dealers/:id/trucks/new', to: 'trucks#new', as: 'new_truck'
  post '/dealers/:id/trucks', to: 'trucks#create', as: 'create_truck'
  get '/trucks/:id/edit', to: 'trucks#edit', as: 'edit_truck'
  patch '/trucks/:id', to: 'trucks#update', as: 'update_truck'
  get '/trucks/:id', to: 'trucks#show', as: 'show_truck'
  delete '/trucks/:id', to: 'trucks#destroy', as: 'destroy_truck'

  get '/dealers/:id/trucks', to: 'trucks_dealer#index', as: 'trucks_dealer'
  get '/roads/:id/cars', to: 'cars_road#index', as: 'cars_road'
end

app/models/dealer.rb
require 'Time'
class Dealer < ApplicationRecord
  has_many :trucks, dependent: :destroy

  def self.date_time_sort
    Dealer.order("open DESC, created_at DESC")
  end

  def self.update_date_time_sort
    Dealer.order(updated_at: 'desc')
  end

  def time_format
    created_at.strftime('%m/%d/%Y')
  end

  def self.sort_by_trucks_count
    Dealer.all.sort_by {|dealer| -dealer.child_count(:trucks)}
  end

  def sort_alphabetically
    trucks.order('LOWER(make) ASC')
  end

  def partial_search(find)
    key = "%#{find}%"

    trucks.where("make || model like :search", search: key)
  end

  def exact_search(find)
    key = "#{find}"

    trucks.where("make = :finder", finder: key) || Truck.where("make = :finder", finder: key)
  end

  def search_year(search)
    trucks.where("year >= ?", search)
  end
end

app/controllers/dealers_controller.rb
class DealersController < ApplicationController
  def index
    if params["commit"] == "Sort Dealers by Trucks count"
      @dealers = Dealer.sort_by_trucks_count
    else
      @dealers = Dealer.date_time_sort
    end
  end

  def show
    @dealer = Dealer.find(params[:id])
  end

  def new
  end

  def create
    if params[:name] == ""
      redirect_to "/dealers/new"
    else
      dealer = Dealer.new(dealer_params)
      dealer.save
      redirect_to '/dealers'
    end
  end

  def edit
    @dealer = Dealer.find(params[:id]).trucks
    render "/dealers/edit.html.erb"
  end

  def update
    if params[:name] == ""
      redirect_to edit_dealer_path(params[:id])
    else
      dealer = Dealer.find(params[:id])
      dealer.update(dealer_params)
      redirect_to show_dealer_path(dealer.id)
    end
  end

  def destroy
    Dealer.destroy(params[:id])
    redirect_to dealers_path
  end
end

private

def dealer_params
  params.permit(:name, :city, :state, :open)
end

app/views/dealers/edit.html.erb
<%= form_tag update_dealer_path(params[:id]), method: :patch do  %>
  <%= label_tag 'name:' %>
  <%= text_field_tag :name %><br><br>
  <%= label_tag 'city:' %>
  <%= text_field_tag :city %><br><br>
  <%= label_tag 'state:' %>
  <%= text_field_tag :state %><br><br>
  <h3>Dealer Open?</h3>
  <%= label_tag('yes') %>
  <%= radio_button_tag('open', 'true') %>
  <%= label_tag('no') %>
  <%= radio_button_tag('open', 'false', required: 'required') %>
  <div>
    <%= submit_tag "update" %>
  </div>
<% end %>

app/views/dealers/index.html.erb
<html>
  <head>
    <meta http-equiv="content-type" content="text/html; charset=utf-8" />
  </head>

  <body>
    <ul class="navbar">
      <li><%= link_to "Home Page", home_path, method: :get %></li>
      <li><%= link_to "Trucks Index", "/trucks", method: :get %></li>
      <li><%= link_to "Add a Dealer", new_dealer_path, method: :get %></li>
    </ul>
    <h1 id="mainheader"> All Dealers</h1>
    <%= form_tag dealers_path, method: :get do %>
      <div>
        <%= submit_tag 'Sort Dealers by Trucks count' %>
      </div>
    <% end %><br>
    <table style="  border: 1px solid black;">
      <tr>
        <th>Dealer Name</th>
        <th>Truck Count</th>
        <th>Creation Date</th>
        <th>Edit</th>
        <th>Delete</th>
      </tr>
      <% @dealers.each do |dealer| %>
        <tr>
          <td><%= link_to dealer.name, show_dealer_path(dealer.id), method: :get %></td>
          <td><%= "#{dealer.child_count(:trucks)} Trucks" %>
          <td><%= dealer.time_format %></td>
          <td><%= link_to "Edit", edit_dealer_path(dealer.id), method: :get %></td>
          <td><%= link_to 'Delete', destroy_dealer_path(dealer.id), method: :delete %></td>
        </tr>
      <% end %>
    </table>
  </body>
</html>

app/views/dealers/new.html.erb
<%= form_tag create_dealer_path, method: :post do  %>
  <%= label_tag 'name:' %>
  <%= text_field_tag :name %><br><br>
  <%= label_tag 'city:' %>
  <%= text_field_tag :city %><br><br>
  <%= label_tag 'state:' %>
  <%= text_field_tag :state %><br><br>
  <h3>Dealer Open?</h3>
  <%= label_tag('yes') %>
  <%= radio_button_tag('open', 'true') %>
  <%= label_tag('no') %>
  <%= radio_button_tag('open', 'false', required: 'required') %>
  <div>
    <%= submit_tag "create" %>
  </div>
<% end %>

app/views/dealers/show.html.erb
<html>
  <head>
  </head>

  <body>
    <ul class="navbar">
      <li><%= link_to "Home Page", home_path, method: :get %></li>
      <li><%= link_to "Dealers Index", dealers_path, method: :get %></li>
      <li><%= link_to "Trucks Index", trucks_path, method: :get %></li>
      <li><%= link_to "#{@dealer.name} Trucks", trucks_dealer_path, method: :get %></li>
      <li><%= link_to "Edit", edit_dealer_path(@dealer.id), method: :get %></li>
      <li><%= link_to "Delete", destroy_dealer_path(@dealer.id), method: :delete %></li>

    </ul><br/>

    <table>
      <tr>
        <th>Dealer Name</th>
        <th>Location</th>
        <th>Founded</th>
        <th>Open?</th>
      </tr>
      <tr>
        <td><%= @dealer.name %></td>
        <td><%= @dealer.city + ", " + @dealer.state %></td>
        <td><%= @dealer.created_at %></td>
        <td><%= @dealer.open %></td>
      </tr>
    </table>
  </body>
</html>